version: "3.8"

volumes:
  postgres-data:

services:
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    env_file:
      - .env

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  program:
    build:
      context: .
      dockerfile: ./program/Dockerfile
    env_file:
      - .env

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    env_file:
      - .env

    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    depends:
      - auth
      - program

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
